name: Swift
on: [push]
jobs:

  macos:
    name: macOS
    runs-on: macos-15
    strategy:
      matrix:
        config: ["debug", "release"]
        options: ["", "SWIFT_BUILD_DYNAMIC_LIBRARY=1"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Swift Version
      run: swift --version
    - name: Build
      run: ${{ matrix.options }} swift build -c ${{ matrix.config }}
    - name: Test
      run: ${{ matrix.options }} swift test -c ${{ matrix.config }}
  
  linux:
    name: Linux
    strategy:
      matrix:
        container: ["swift:6.0.3", "swift:6.1.2"]
        config: ["debug", "release"]
        options: ["", "SWIFT_BUILD_DYNAMIC_LIBRARY=1"]
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}-jammy
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Swift Version
      run: swift --version
    - name: Build
      run: ${{ matrix.options }} swift build -c ${{ matrix.config }}
    - name: Test
      run: ${{ matrix.options }} swift test -c ${{ matrix.config }}
    - name: Build (Debug)
      run: swift build -c debug
    - name: Build (Release)
      run: swift build -c release
    - name: Test (Debug)
      run: swift test -c debug
